version: "3"
services:
  postgres:
    container_name: nestjs-postgres-books
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/docker-data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ~/docker-data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge